import type { OchreInkContent } from '../ochre-ink.schema';

export const ochreInkFixture: OchreInkContent = {
  summit: {
    name: 'ADHD Parenting Summit 2026',
    tagline: 'Real strategies for real families',
    startDate: '2026-04-22',
    endDate: '2026-04-26',
  },
  masthead: {
    volume: 'Vol. VII · Feb 2026',
    eyebrow: 'An Annual Reader',
  },
  hero: {
    issueLabel: 'Issue No. VII',
    dateRangeLabel: 'Feb 10–14, 2026',
    metaLabel: '100% Free · Online',
    readerCount: '73,124 Readers',
    eyebrow: 'A Five-Day Editorial Series for Parents',
    headline: 'The Child You Were Told Was Too Much Is, In Fact, Right On Time.',
    subheadline: 'Forty of the field\'s most patient minds gather for five days to answer the questions you\'ve been asking alone at 2 a.m.',
    ctaLabel: 'Reserve your seat',
    ctaSubtext: 'Registration closes Feb 9 at midnight. A complimentary Parenting Collection is enclosed with every seat.',
    ratingText: 'Loved by 73,124 committed parents',
    figCaption: "Fig. 1 — A selection of this issue's contributors",
    heroSpeakerIds: [
      '11111111-1111-4111-8111-111111111111',
      '22222222-2222-4222-8222-222222222222',
      '33333333-3333-4333-8333-333333333333',
      '44444444-4444-4444-8444-444444444444',
    ],
  },
  featuredIn: [
    'The New York Times',
    'The Atlantic',
    'The Guardian',
    'Psychology Today',
    'The Washington Post',
    'TIME',
    'Scientific American',
    'TEDx',
    'Forbes',
    'BBC',
  ],
  socialProof: {
    statLabel1: 'days of live, unhurried conversation', statValue1: '5',
    statLabel2: 'experts, clinicians, and writers', statValue2: '40+',
    statLabel3: "parents who've attended before you", statValue3: '50K',
  },
  whatIsThis: {
    roman: 'II.',
    headline: 'An Unhurried Answer to an Overwhelming Question',
    bodyParagraphs: [
      "We built the ADHD Parenting Summit because we could not find the thing we needed: a generous, evidence-based conversation that treats ADHD parenting as something other than a problem to be fixed.",
      'Watch live or catch the replays at your own pace. The sessions are free. The strategies are real. The relief is, we hope, audible.',
    ],
    ctaLabel: 'Claim your seat',
  },
  featureBand: {
    eyebrow: "Editors' Note",
    headline: "Editors' Note",
    body: "A three-part preface to the issue.",
    bullets: [
      'Five evenings, not five weeks. Sessions run 90 minutes each, roughly in the hour after dinner.',
      'Forty contributors. Neuropsychologists, family therapists, educators, and parents who have been where you are now.',
      'A complimentary Collection. Scripts, templates, and checklists — sent by email on registration. Yours to keep.',
    ],
  },
  speakersByDay: [
    {
      dayLabel: 'Contributors — Day One',
      dayDate: '2026-04-22',
      dayTheme: "Understanding Your Child's Brain",
      roman: 'III.',
      speakerIds: [
        '11111111-1111-4111-8111-111111111111',
        '22222222-2222-4222-8222-222222222222',
        '33333333-3333-4333-8333-333333333333',
        '44444444-4444-4444-8444-444444444444',
      ],
    },
  ],
  transformations: {
    roman: 'IV.',
    headline: 'Six Transformations, One Week.',
    subhead: 'What the end of Day Five may sound like at your kitchen table.',
    items: [
      { title: 'Understand Why They Act Out', description: 'The neuroscience behind the behavior — so "bad child" becomes "dysregulated nervous system."' },
      { title: 'End the Yelling Cycle', description: 'Calm responses that actually work — not because you found willpower, but because you found a different script.' },
      { title: 'Fix Morning Chaos', description: 'A small collection of routines that reduce daily friction. Things that hold up in real kitchens.' },
      { title: 'Build Emotional Resilience', description: 'Help your child regulate big emotions — not suppress them. The difference, over time, changes everything.' },
      { title: 'Navigate School Systems', description: 'IEPs, 504s, and the quiet art of teacher communication. Language that is firm, warm, and hard to refuse.' },
      { title: 'Connect With Other Parents', description: 'A quiet side-channel for those late-night questions. You are not alone in this.' },
    ],
  },
  supplement: {
    cardLabel: 'Supplement',
    cardTitle: 'The ADHD Parenting Mastery Collection',
    cardFooter: 'Issued with your complimentary seat',
    cardVolume: 'Vol. VII · 2026',
    badgeLabel: 'ENCLOSED FREE',
    eyebrow: 'Issued with Registration',
    headline: 'A Collection, Enclosed.',
    body: "A bound selection of scripts, templates, and quiet checklists — drawn from our contributors' clinical practice and printed for the kitchen drawer. Your copy arrives the moment you register.",
    bullets: [
      'Morning-routine visual schedules, tested in real homes.',
      'De-escalation scripts for meltdowns — the first sentence matters most.',
      'IEP & 504 request templates. Firm, warm, hard to refuse.',
      'A printable calm-down card set for the refrigerator door.',
    ],
    ctaLabel: 'Claim Your Seat & Supplement',
  },
  bonusStackSection: {
    roman: 'V.',
    headline: 'Three Sidebars, Three Bonuses.',
    subhead: 'Worth $291 in print. Enclosed with every seat.',
    ctaLabel: 'Claim Seat + All Three Sidebars',
  },
  bonusStack: [
    {
      title: 'The ADHD Morning Playbook',
      description: 'A seven-day system for transforming chaotic mornings into calm, connected starts to the day.',
      valueLabel: '$97 VALUE',
      bullets: ['Visual-schedule templates', 'Transition scripts that work', 'A calm-down toolkit'],
    },
    {
      title: 'Meltdown to Breakthrough',
      description: 'A step-by-step de-escalation framework that turns outbursts into growth moments.',
      valueLabel: '$97 VALUE',
      bullets: ['Five-step de-escalation method', 'Emotional-coaching scripts', 'Printable calm-down cards'],
    },
    {
      title: 'School Advocacy Toolkit',
      description: 'Everything you need to get your child the support they deserve at school.',
      valueLabel: '$97 VALUE',
      bullets: ['IEP/504 request templates', 'Teacher-communication scripts', 'Accommodation checklists'],
    },
  ],
  founders: {
    roman: 'VI.',
    headline: 'From the Founders',
    items: [
      {
        name: 'Roman Wiltman',
        role: 'Co-Founder',
        quote: 'Our journey started when our son was diagnosed at six. We felt lost, overwhelmed, and alone. This summit exists so that no other parent has to.',
        initials: 'RW',
      },
      {
        name: 'Anisah Semen',
        role: 'Co-Founder',
        quote: 'Every child with ADHD has incredible strengths waiting to be unlocked. Our mission is to help parents see those strengths — and, gently, to nurture them.',
        initials: 'AS',
      },
    ],
  },
  testimonials: {
    roman: 'VII.',
    headline: 'Letters to the Editor',
    subhead: 'A sampling from 73,124 past readers.',
    items: [
      { quote: 'This summit was life-changing. The expert sessions gave me tools I use every single day. My relationship with my son has completely transformed.', name: 'Rachel Berman', location: 'Ohio, USA', initials: 'RB' },
      { quote: "Finally — someone who understands. The strategies are practical, not theoretical. My daughter's mornings are so much calmer now.", name: 'Kamila Bosco', location: 'London, UK', initials: 'KB' },
      { quote: "My husband and I watched together. For the first time we're on the same page about how to support our ADHD child. That alone was worth it.", name: 'Jennifer Mitchell', location: 'Toronto, CA', initials: 'JM' },
    ],
  },
  pullQuote: {
    quote: 'The earlier you learn how to support your child with ADHD, the better your chances of managing their condition and minimizing long-term challenges.',
    attribution: 'Dr. Sarah Jensen · Neuropsychologist',
  },
  figures: {
    roman: 'VIII.',
    headline: 'The Reality of ADHD in Families Today',
    subhead: 'Six figures, drawn from clinical research and our 2025 reader survey.',
    items: [
      { label: 'Fig. 1', value: '1 in 9', description: 'Children diagnosed with ADHD in the US' },
      { label: 'Fig. 2', value: '74%', description: 'Of parents feel isolated and unsupported' },
      { label: 'Fig. 3', value: '3.2×', description: 'Higher reported stress in ADHD families' },
      { label: 'Fig. 4', value: '15+', description: 'Years of clinical research represented' },
      { label: 'Fig. 5', value: '28%', description: 'Of school-age children struggle academically' },
      { label: 'Fig. 6', value: '93%', description: 'Of past attendees recommend this summit' },
    ],
  },
  shifts: {
    roman: 'IX.',
    headline: 'What Changes by Day Five',
    items: [
      { title: 'From Punishment to Partnership', description: 'Move beyond punishment-based parenting to an evidence-backed approach that builds cooperation naturally.' },
      { title: 'From Reacting to Anticipating', description: 'See the meltdown coming twenty minutes out, and redirect the nervous system before the room is on fire.' },
      { title: 'From Isolated to Supported', description: 'Join a cohort of parents who have been where you are. The 2 a.m. texts stop being a solo act.' },
      { title: 'From Overwhelmed to Equipped', description: 'Trade vague anxiety for specific language and tools. You will know, concretely, what to say on Monday at 7:42 a.m.' },
      { title: 'From Shame to Sovereignty', description: "Your child's neurology is not a verdict on your parenting. This becomes a lived fact — not a mantra you have to repeat." },
    ],
  },
  faqs: [
    { question: 'Is it really free?', answer: "Yes, entirely. All forty sessions, the supplement, and the three bonus sidebars. You'll receive upgrade offers later — these are optional and never gate the free content." },
    { question: 'What if I miss a live session?', answer: 'Each session is recorded and available for 48 hours after it airs. Registered readers with the All-Access Pass keep permanent access to every recording.' },
    { question: "Is this suitable if my child isn't formally diagnosed?", answer: 'Absolutely. Many of our attendees are observing ADHD traits and deciding whether to pursue assessment. The content is relevant regardless of diagnostic status.' },
    { question: 'My partner wants to attend too — do they need a separate seat?', answer: 'One registration covers your household. Bring your partner, grandparents, co-parent, or an older child if appropriate.' },
    { question: 'Is medical advice offered?', answer: "Our contributors are qualified clinicians, but the summit is educational, not clinical. We'll point you toward where to go for personalized medical guidance." },
  ],
  closing: {
    eyebrow: 'Reservation Closes Feb 9',
    headline: 'Your copy of Issue VII is ready.',
    subheadline: "Five days with forty of the field's most thoughtful minds — yours, free, delivered to your inbox.",
    ctaLabel: 'Reserve Your Seat',
    fineprint: 'Free · No credit card · Unsubscribe anytime',
  },
  footer: {
    tagline: 'Issued annually, to the households who need it most.',
    volume: 'Vol. VII · February 2026',
    copyright: '© 2026 Althea Academy. All rights reserved.',
  },
};
