@php
    /** @var \App\Models\FunnelStep $step */
    $step = $getRecord();
    $funnel = $step?->funnel;
    $pageContent = (array) ($step?->page_content ?? []);
    $templateKey = $pageContent['template_key'] ?? null;
    $palette = array_slice(array_values((array) ($pageContent['palette'] ?? [])), 0, 5);
    $enabled = (array) ($pageContent['enabled_sections'] ?? []);

    $registry = app(\App\Services\Templates\TemplateRegistry::class);
    $label = $templateKey ? ($registry->exists($templateKey) ? ($registry->get($templateKey)['label'] ?? $templateKey) : $templateKey) : 'Generated page';

    $draft = $step ? \App\Models\LandingPageDraft::query()
        ->whereHas('batch', fn ($q) => $q->where('funnel_step_id', $step->id))
        ->orderByRaw("CASE WHEN status = 'published' THEN 0 ELSE 1 END")
        ->latest()
        ->first() : null;

    $editUrl = ($funnel && $draft)
        ? \App\Filament\Resources\Funnels\FunnelResource::getUrl('edit-landing-page-draft', [
            'record' => $funnel->id,
            'draft' => $draft->id,
        ])
        : null;

    $previewBase = rtrim((string) config('next.url', 'http://localhost:3000'), '/');
    $previewUrl = ($draft && $draft->preview_token) ? "{$previewBase}/preview/{$draft->preview_token}" : null;
@endphp

<div style="display:flex;gap:20px;align-items:center;justify-content:space-between;padding:20px;border:1px solid #bae6fd;border-radius:12px;background:linear-gradient(135deg,#f0f9ff 0%,#ffffff 60%)">
    <div style="display:flex;align-items:center;gap:16px;min-width:0">
        <div style="width:44px;height:44px;border-radius:10px;background:linear-gradient(135deg,#0ea5e9,#6366f1);flex-shrink:0;display:flex;align-items:center;justify-content:center;color:#fff;font-weight:700;font-size:18px">AI</div>
        <div style="display:flex;flex-direction:column;gap:6px;min-width:0">
            <div style="font-size:15px;font-weight:700;color:#0f172a">Generated by {{ $label }}</div>
            <div style="font-size:12px;color:#64748b">
                {{ count($enabled) }} section{{ count($enabled) === 1 ? '' : 's' }} enabled. Edit, reorder, or swap sections in the draft editor.
            </div>
            @if ($palette)
                <div style="display:flex;align-items:center;gap:6px;font-size:12px;color:#64748b">
                    <span>palette:</span>
                    <span style="display:inline-flex;gap:2px">
                        @foreach ($palette as $swatch)
                            <span style="width:14px;height:14px;border-radius:3px;border:1px solid rgba(0,0,0,.08);background:{{ $swatch }}"></span>
                        @endforeach
                    </span>
                </div>
            @endif
        </div>
    </div>
    <div style="display:flex;flex-direction:column;gap:8px;flex-shrink:0">
        @if ($previewUrl)
            <a href="{{ $previewUrl }}" target="_blank" rel="noopener"
               style="padding:6px 12px;border:1px solid #e2e8f0;border-radius:8px;background:#fff;color:#334155;font-size:13px;font-weight:500;text-align:center;text-decoration:none">Preview</a>
        @endif
        @if ($editUrl)
            <a href="{{ $editUrl }}"
               style="padding:6px 12px;border:1px solid #0ea5e9;border-radius:8px;background:#0ea5e9;color:#fff;font-size:13px;font-weight:600;text-align:center;text-decoration:none">Edit sections</a>
        @else
            <span style="padding:6px 12px;border:1px dashed #cbd5e1;border-radius:8px;color:#64748b;font-size:13px;text-align:center">No draft found</span>
        @endif
    </div>
</div>
