// next-app/src/lib/themes/parenting-summits.ts
export const parentingSummitsTheme = {
  palette: {
    primary: '#704fe6',
    primary_dark: '#5e4d9b',
    primary_deep: '#4831B0',
    primary_text: '#ffffff',
    cta: '#FBA506',
    cta_secondary: '#ffc500',
    cta_orange: '#ff8f00',
    accent_red: '#b83b4b',
    accent_green: '#00b553',
    background: '#ffffff',
    surface: '#e6e6fa',
    surface_translucent: 'rgba(196,190,218,0.96)',
    text: '#000000',
    text_muted: '#898686',
    text_light: '#a9a9a9',
    border: '#e5e7eb',
  },
  typography: {
    heading_font: 'Poppins',
    body_font: 'Poppins',
    accent_font: 'Cormorant Garamond',
    social_proof_font: 'Raleway',
    heading_weight: 700,
    scale: {
      h1: '48px',
      h2: '32px',
      h3: '24px',
      h4: '20px',
      body: '18px',
      body_sm: '16px',
      label: '14px',
      tiny: '12px',
    },
    line_height: {
      heading: 1.2,
      body: 1.4,
      relaxed: 1.6,
    },
  },
  components: {
    button_shape: 'pill',
    button_radius: '500px',
    button_radius_sm: '15px',
    button_weight: 'bold',
    card_style: 'elevated',
    card_radius: '12px',
  },
  rhythm: {
    section_padding_lg: '75px',
    section_padding_md: '50px',
    section_padding_sm: '24px',
    section_padding_x: '20px',
    max_width: '1120px',
    content_width_narrow: '740px',
    grid_gap: '20px',
    density: 'comfortable',
  },
  voice: {
    tone: 'warm-expert',
    headline_style: 'benefit-driven',
  },
  hero_pattern: 'split-image-right',
  responsive: {
    tablet: '991px',
    mobile: '767px',
    small_mobile: '479px',
  },
};
