<?php

namespace App\Filament\Resources\FunnelSteps;

use App\Filament\Resources\FunnelSteps\Pages;
use App\Models\FunnelStep;
use BackedEnum;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteAction;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ViewAction;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Resources\Resource;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Filters\TernaryFilter;
use Filament\Tables\Table;

class FunnelStepResource extends Resource
{
    protected static ?string $model = FunnelStep::class;

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedRectangleStack;

    protected static string|\UnitEnum|null $navigationGroup = 'Funnels';

    protected static ?int $navigationSort = 20;

    protected static ?string $recordTitleAttribute = 'name';

    public static function form(Schema $schema): Schema
    {
        return $schema->components([
            Section::make('Step')
                ->columns(2)
                ->components([
                    Select::make('funnel_id')
                        ->label('Funnel')
                        ->relationship('funnel', 'name')
                        ->required()
                        ->searchable()
                        ->preload(),
                    Select::make('step_type')
                        ->options([
                            'optin' => 'Opt-in',
                            'sales_page' => 'Sales page',
                            'checkout' => 'Checkout',
                            'upsell' => 'Upsell',
                            'downsell' => 'Downsell',
                            'thank_you' => 'Thank you',
                        ])
                        ->required()
                        ->native(false),
                    TextInput::make('name')->required()->maxLength(500),
                    TextInput::make('slug')->required()->maxLength(255),
                    Select::make('product_id')
                        ->label('Product (for checkout/upsell)')
                        ->relationship('product', 'name')
                        ->searchable()
                        ->preload()
                        ->placeholder('No product linked'),
                    TextInput::make('sort_order')->numeric()->default(0),
                    Toggle::make('is_published')->default(false),
                ]),

            Section::make('Page content')
                ->description('JSONB block tree describing how the page looks. Typically generated by the AI builder — edit manually only if you know what you\'re doing.')
                ->components([
                    Textarea::make('page_content_json')
                        ->label('Page content (JSON)')
                        ->rows(12)
                        ->dehydrated(false)
                        ->formatStateUsing(fn ($state, ?FunnelStep $record): string => json_encode($record?->page_content ?? [], JSON_PRETTY_PRINT))
                        ->afterStateUpdated(function ($state, callable $set): void {
                            $decoded = json_decode((string) $state, true);
                            if (is_array($decoded)) {
                                $set('page_content', $decoded);
                            }
                        })
                        ->helperText('Raw JSON. Empty object = {} means no content yet.'),
                ]),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('name')
                    ->searchable()
                    ->sortable()
                    ->weight('bold'),
                TextColumn::make('funnel.name')->label('Funnel')->searchable()->toggleable(),
                TextColumn::make('step_type')
                    ->badge()
                    ->formatStateUsing(fn (string $state) => str_replace('_', ' ', $state))
                    ->color(fn (string $state): string => match ($state) {
                        'optin' => 'info',
                        'sales_page' => 'primary',
                        'checkout' => 'success',
                        'upsell', 'downsell' => 'warning',
                        'thank_you' => 'gray',
                        default => 'gray',
                    }),
                TextColumn::make('product.name')->label('Product')->toggleable(),
                TextColumn::make('sort_order')->alignCenter()->sortable(),
                IconColumn::make('is_published')->boolean(),
            ])
            ->filters([
                SelectFilter::make('funnel_id')
                    ->relationship('funnel', 'name')
                    ->label('Funnel')
                    ->preload(),
                SelectFilter::make('step_type')->options([
                    'optin' => 'Opt-in',
                    'sales_page' => 'Sales page',
                    'checkout' => 'Checkout',
                    'upsell' => 'Upsell',
                    'downsell' => 'Downsell',
                    'thank_you' => 'Thank you',
                ]),
                TernaryFilter::make('is_published'),
            ])
            ->recordActions([
                ViewAction::make(),
                EditAction::make(),
                DeleteAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ])
            ->defaultSort('sort_order');
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListFunnelSteps::route('/'),
            'create' => Pages\CreateFunnelStep::route('/create'),
            'view' => Pages\ViewFunnelStep::route('/{record}'),
            'edit' => Pages\EditFunnelStep::route('/{record}/edit'),
        ];
    }
}
