/**
 * Payload Admin Import Map
 *
 * Auto-generated by `payload generate:importMap`.
 * Do not edit manually — run `npm run generate:types` to regenerate.
 *
 * This file maps component paths to their actual module imports so that
 * Payload's admin UI can lazy-load custom components without bundling issues.
 */
export const importMap = {}
